if [ "${SIRIUS_EXTENSION+x}" = x ]; then
  export SIRIUS_EXTENSION_CONDA_BACKUP="${SIRIUS_EXTENSION}"
  export SIRIUS_EXTENSION_CONDA_HAD_VALUE=1
else
  unset SIRIUS_EXTENSION_CONDA_BACKUP
  unset SIRIUS_EXTENSION_CONDA_HAD_VALUE
fi
export SIRIUS_EXTENSION="${CONDA_PREFIX}/lib/sirius.duckdb_extension"
