if [ "${SIRIUS_EXTENSION_CONDA_HAD_VALUE:-0}" = 1 ]; then
  export SIRIUS_EXTENSION="${SIRIUS_EXTENSION_CONDA_BACKUP}"
else
  unset SIRIUS_EXTENSION
fi
unset SIRIUS_EXTENSION_CONDA_BACKUP
unset SIRIUS_EXTENSION_CONDA_HAD_VALUE
